
<HTML>
<BODY>
<H1>HAI THERE ...GUESSING YOU WERE ALSO A DIE HARD FAN OF TALAIVAR</H1>
<FORM ACTION="new-lang-parser.php" METHOD="POST">
<INPUT TYPE="text" name="t1">
<INPUT TYPE="SUBMIT">
</FORM>
</BODY>
</HTML>